### ISSUE TITLE
Unable to find helpers/helpers-*.js

### ISSUE THREAD

**Issue by gsambrotta** [thierryc/grunt-handlebars-layouts#4] opened 2015-02-20 11:39 UTC
Hi, thank you for your plugin, is really great!
I'm not sure this is a bug or my bad in configurate it but I'm think the configuration is good, or at leats make sense.
I'm able to run the task and compile .hbs in .html but if I try to add helpers I got error:
`Fatal error: Unable to find the src/helpers/helpers-foo.js dependency. Did you install it ?`

My folders are exactly the same of the one in the example folder.
I have Gruntfile.js nest to src and dist.
Inside of src there is helpers
src/helpers/helpers-foo.js

and on my gruntfile.js
modules: ['src/helpers/helpers-foo.js', 'src/helpers/helpers-math.js', 'src/helpers/helpers-md.js', 'src/helpers/helpers-md5.js']

or even:
basePath: 'src/',
modules: ['src/helpers/helpers-*.js']

Do i'm missing soemthing or for some reason it doesn't find the files?

**Comment by thierryc** [comment] 2015-02-21 16:45
Hi, 
isI can't reproduce your bug. 
Can you send me more information about it ?

What is your folder structure ?

 ```

├── partials
|   ├── footer.(html|hsb|md)
|   └── header.(html|hsb|md)
├── pages
|   ├── 2014-08-14-Handlebars-layouts-foo.(html|hsb)
|   └── 2014-08-14-Handlebars-layouts-bar.(html|hsb)
├── data
|   └── members.json
├── helpers
|   └── helpers-*.js
└── index.html

```

**Comment by gsambrotta** [comment] 2015-02-23 18:48
My folder is the same of yours in /exmple.

src folder:
```
├── partials
|   ├── footer.(html|hsb)
|   └── header.(html|hsb)
├── helpers
|   └── helpers-*.js
└── layout.html
|_____ home.hbs
```

And then in Gruntfile.js

`modules: ['src/helpers/helpers-*.js']`

I think we will make the project open source soon, then I can easily link you the whole project and is maybe easier for you to spot the bug

**Comment by thierryc** [comment] 2015-02-23 21:34
Yes. of course.
I close the issue for the moment.
Please, reopen it when you have publish your open source project.

**Comment by ricardomuniz** [comment] 2015-06-14 19:29
I came across this issue yesterday as well. I noticed that I wrote `module.exports.registerHelper` instead of `module.exports.register`. So this issue is more related to the way the helper files are written.

Correct

    module.exports.register = function (Handlebars, options) {
      Handlebars.registerHelper('something', function() {
        ...
      });
    };

Wrong

    module.exports.registerHelper = function (Handlebars, options) {
      Handlebars.registerHelper('something', function() {
        ...
      });
    };

**Comment by thierryc** [comment] 2015-06-15 10:35
Thank you, I fix it as soon as possible !

**Closed** 2015-08-11 11:07 UTC
Labels: enhancement
